export default {
	isLoading: false,
	isLogedIn: false,
	isAdmin: null,
    // constants: {maxCoWorkers:20, maxNonPremiumProjects:3},
	// token: null,
	_id: null,
	// userName: null,
    firstName: null,
	lastName: null,
    profession: null,
    country: null,
    birthday: null,
    friends: null,
    frequests: null,
    myJobs: null,
    myChat: null,

    phoneNum: null,
	profEmail: null,
    perEmail: null,
	image: null,
	
	posts: null,
	notifications: [],
	userStories: [],
	projects: [],

    resume: null,
    workplace: null,
	invites: [],
	coWorkers: [],
}
